export const initialCategories = [
  { id: 'all', name: 'All Notes', count: 4 },
  { id: 'technology', name: 'Technology', count: 2 },
  { id: 'research', name: 'Research', count: 1 },
  { id: 'personal', name: 'Personal', count: 1 },
];

export const initialModels = {
  active_model: 'gpt-4o-mini',
  active_engine: 'langgraph',
  generative_models: [
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini (OpenAI)', provider: 'openai', status: 'active' },
    { id: 'gpt-4o', name: 'GPT-4o (OpenAI)', provider: 'openai', status: 'available' },
    { id: 'mistral:7b-ollama', name: 'Mistral 7B (Ollama Local)', provider: 'ollama', status: 'available' },
    { id: 'llama3:70b-ollama', name: 'Llama 3 70B (Ollama Local)', provider: 'ollama', status: 'available' },
    { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet (Anthropic)', provider: 'anthropic', status: 'available' },
  ],
  embedding_models: [
    { id: 'text-embedding-3-small', name: 'Text Embedding 3 Small (1536d)' },
    { id: 'nomic-embed-text', name: 'Nomic Embed Text (Ollama Local)' },
  ],
};

export const initialNotes = [];

export const mockAuditData = {
  status: 'healthy',
  timestamp: '2026-08-12T19:50:00Z',
  markdown_files_count: 4,
  sqlite_records_count: 4,
  chromadb_chunks_count: 18,
  integrity_drift: false,
  message: 'All 3 storage layers (Markdown, SQLite, ChromaDB) are 100% in sync.'
};

export const mockMetrics = {
  total_memories: 4,
  total_tokens_processed: 18450,
  avg_llm_latency_ms: 312.4,
  vector_search_latency_ms: 18.2,
  active_llm_provider: 'OpenAI (gpt-4o-mini)',
  active_embedding_model: 'text-embedding-3-small',
};

// Simulation helper for LLM Auto-Organize
export function simulateAutoOrganizeNote(content, currentTitle = '', activeModel = 'gpt-4o-mini') {
  const cleanContent = content.trim();
  if (!cleanContent) {
    return {
      status: 'error',
      message: 'Content cannot be empty.'
    };
  }

  const firstLine = cleanContent.split('\n')[0].replace(/^#+\s*/, '').trim();
  const title = currentTitle && currentTitle !== 'Untitled Note' 
    ? currentTitle 
    : (firstLine.slice(0, 40) || 'Auto-Organized Note');

  const wordList = cleanContent.toLowerCase().match(/\b[a-z]{4,}\b/g) || [];
  const freqMap = {};
  wordList.forEach(w => {
    if (!['with', 'that', 'this', 'from', 'have', 'your', 'about', 'note'].includes(w)) {
      freqMap[w] = (freqMap[w] || 0) + 1;
    }
  });
  const tags = Object.keys(freqMap).sort((a, b) => freqMap[b] - freqMap[a]).slice(0, 4);
  if (tags.length === 0) tags.push('general', 'notes');

  let category = 'personal';
  if (cleanContent.toLowerCase().includes('neural') || cleanContent.toLowerCase().includes('ai') || cleanContent.toLowerCase().includes('code')) {
    category = 'technology';
  } else if (cleanContent.toLowerCase().includes('sync') || cleanContent.toLowerCase().includes('arch') || cleanContent.toLowerCase().includes('db')) {
    category = 'architecture';
  } else if (cleanContent.toLowerCase().includes('audit') || cleanContent.toLowerCase().includes('research')) {
    category = 'research';
  }

  const summary = `Executive summary generated by ${activeModel}: "${cleanContent.slice(0, 110)}..."`;
  const organizedContent = `# ${title}\n\n${cleanContent}\n\n--- \n*Auto-formatted and summarized via ${activeModel} engine.*`;

  return {
    status: 'success',
    title,
    category,
    tags,
    summary,
    organized_content: organizedContent
  };
}

// Simulation helper for LLM Smart Merge & Memory Modification
export function simulateSmartMergeNote(content, existingNote, activeModel = 'gpt-4o-mini') {
  const title = existingNote?.title || 'Merged Memory Note';
  const category = existingNote?.category || 'personal';
  const existingTags = existingNote?.tags || ['memory'];
  const mergedTags = Array.from(new Set([...existingTags, 'llm_merged']));
  const summary = `Contextual memory merge generated by ${activeModel} engine.`;
  const mergedContent = `# ${title}\n\n${content}\n\n--- \n*Contextual LLM memory update merged via ${activeModel}.*`;

  return {
    status: 'success',
    title,
    category,
    tags: mergedTags,
    summary,
    organized_content: mergedContent
  };
}

export function simulateGraphChat(query) {
  return {
    status: 'success',
    message: query,
    reply: `I searched across your active memories using hybrid semantic search and LangGraph reasoning.\n\nBased on your query **"${query}"**, I found relevant insights in *Neural Network Pruning* and *GraphRAG Architecture*. Would you like me to synthesize a detailed summary or save a new memory topic?`,
    entities: ['Pruning', 'GraphRAG', 'ChromaDB'],
    latency_ms: 245.8,
  };
}
